language: ruby

bundler_args: --without debugger

cache: bundler
sudo: false

before_install:
  - gem --version

script: bundle exec rspec

rvm:
  - 2.4.1
  - 2.5.0
  - 2.4
  - 2.7
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.2.7
    - rvm: 2.3.4

notifications:
  email:
    recipients:
      - ngiger@ywesee.com
      - yasaka@ywesee.com
      - zdavatz@ywesee.com
